### ISSUE TITLE
What is the proper way to use Serum_ColorizeOrApplyRotations?

### ISSUE THREAD

**Issue by jsm174** [zesinger/libserum#32]
To support serum rotations, libpinmame was recently updated to call `OnDisplayUpdated` on every cycle regardless of if the frame actually changed or not.  To know if the frame changed, `p_displayData` will not be null.

So the new loop for `OnDisplayUpdated` in VPX Standalone is like this:

```
if (Serum_ColorizeOrApplyRotations(pController->m_pDmdData, p_displayLayout->width, p_displayLayout->height, pController->m_dmdPalette, NULL))
   pController->m_dmdUpdate = true;

if (pController->m_dmdUpdate)
   pController->m_zedmd.RenderColoredGray6(pController->m_pDmdData, pController->m_dmdPalette, p_displayLayout->width, p_displayLayout->height);
```

Upon calling `Serum_ColorizeOrApplyRotations`, if it is a new frame, I'm assuming `m_pDmdData` and `m_dmdPalette` get changed. If it is just a rotation, I'm guessing only `m_dmdPalette` should be changing?

I'm seeing this strange behavior where in Scared Stiff, the `Press Start` is getting a weird background. In Tron, I get a flickering box to the left of the Participate In Local Tournaments.

https://github.com/zesinger/libserum/assets/1197137/ac2c89a7-d688-441a-b87d-d2a68d8a3865

https://github.com/zesinger/libserum/assets/1197137/69a2758c-f652-4010-8ed3-bec1bfd88354

Should `m_pDmdData`, always be the non-changed frame from `libpinmame` or is `Serum_ColorizeOrApplyRotations` smart enough to just update the palette in these situations?

**Comment by jsm174** [comment]
Yesterday I noticed the flicker in SS, only happens when not having 1/2 credit:

https://github.com/zesinger/libserum/assets/1197137/81e53d04-5b91-4fb6-b9ab-0a5a35d06aa8

In Tron I noticed I didn't get the flicker (but I don't get the stripe) if I built standalone with GCC as opposed to Clang.  Whenever I've seen weird GCC / Clang differences, it was usually because a variable wasn't initialized??

https://github.com/zesinger/libserum/assets/1197137/2b38bbd3-f168-4246-9ba0-8aedcb92d224



Just a thought.. @mkalkbrenner

**Comment by mkalkbrenner** [comment]
> To support serum rotations, libpinmame was recently updated to call OnDisplayUpdated on every cycle regardless of if the frame actually changed or not. To know if the frame changed, p_displayData will not be null.

This makes sense if you want to render directly on the screen using libserum.
If you want to drive ZeDMD, this is the wrong way. ZeDMD handles the rotations on its own and should only receive a new frame if it changed.

**Comment by jsm174** [comment]
Here are the several different versions I have tried:

1) 

```
bool Serum::Convert(UINT8* frame, UINT8* dstFrame, UINT8* dstPalette)
{
   if (frame)
      memcpy(m_frame, frame, m_frameSize);

   unsigned int triggerId;

   if (Serum_ColorizeOrApplyRotations(m_frame, m_width, m_height, m_palette, &triggerId)) {
      memcpy(dstFrame, m_frame, m_frameSize);
      memcpy(dstPalette, m_palette, 192);

      return true;
   }

   return false;
}
```

**Result**: Flicker. Rotations seem to have correct timing

https://github.com/zesinger/libserum/assets/1197137/cbcc93e7-00bb-4b32-aa8e-42d5b1037ef1


2)

```
bool Serum::Convert(UINT8* frame, UINT8* dstFrame, UINT8* dstPalette)
{
   if (!frame)
      return false;
   
   memcpy(m_frame, frame, m_frameSize);

   unsigned int triggerId;

   if (!Serum_Colorize(m_frame, m_width, m_height, m_palette, m_rotations, &triggerId))
      return false;

   memcpy(dstFrame, m_frame, m_frameSize);
   memcpy(dstPalette, m_palette, 192);

   return true;
}
```

**Result**: No flicker. No Rotation. 

https://github.com/zesinger/libserum/assets/1197137/f8083294-38d1-491e-987b-f013e797531a

3)

```
bool Serum::Convert(UINT8* frame, UINT8* dstFrame, UINT8* dstPalette)
{
   if (frame)
      memcpy(m_frame, frame, m_frameSize);

   unsigned int triggerId;

   if (Serum_Colorize(m_frame, m_width, m_height, m_palette, m_rotations, &triggerId)) {
       memcpy(dstFrame, m_frame, m_frameSize);
       memcpy(dstPalette, m_palette, 192);

       return true;
   }

   return false;
}
```

**Result**: No flicker. No Rotation.

https://github.com/zesinger/libserum/assets/1197137/1dd30bcd-09b9-4e1e-af6a-080a10ccb975

4)

```
bool Serum::Convert(UINT8* frame, UINT8* dstFrame, UINT8* dstPalette)
{
   bool update = false;

   if (frame) {
       memcpy(m_frame, frame, m_frameSize);

       unsigned int triggerId;

       update = Serum_Colorize(m_frame, m_width, m_height, m_palette, m_rotations, &triggerId);
   }
   else {
       update = Serum_ApplyRotations(m_palette, m_rotations);
   }

   if (update) {
      memcpy(dstFrame, m_frame, m_frameSize);
      memcpy(dstPalette, m_palette, 192);
   }

   return update;
}
```

**Result**: No flicker. Rotation at incorrect speed

https://github.com/zesinger/libserum/assets/1197137/793e1d19-d112-4980-a05a-5abb142cddbd

**Comment by mkalkbrenner** [comment]
I assume, we solved that issue

**Comment by jsm174** [comment]
yup, fixed with 

https://github.com/zesinger/libserum/commit/40fb09c663df4ad308b0cad4e47eaa6d687a20cb#diff-78c29ad0d127b90fa71e2834b6ddac5f31f30df50d80c64cac80b9eab1708a19R899

Thank you @mkalkbrenner and @zesinger for the countless questions and research on this.

Below is the correct way to use this function:

```
bool Serum::Convert(UINT8* frame, UINT8* dstFrame, UINT8* dstPalette)
{
   if (frame)
      memcpy(m_frame, frame, m_frameSize);

   unsigned int triggerId;

   bool update = Serum_ColorizeOrApplyRotations(frame ? m_frame : NULL, m_width, m_height, m_palette, &triggerId);

   if (update) {
      memcpy(dstFrame, m_frame, m_frameSize);
      memcpy(dstPalette, m_palette, 192);
   }

   return update;
}
```

**Comment by zesinger** [comment]
My pleasure, I'm happy I eventually fixed that issue!
