### ISSUE TITLE
Identify_Frame function possible bug

### ISSUE THREAD

**Issue by JarekC-DIY** [zesinger/libserum#57]
serum_decode.cpp
function Identify_Frame line 919
_if (first_match || ti != lastfound || mask < 255)_

Condition is met for each frame with a mask.
And what about the sequence:
Ex. lastfound = ID5

_Hashc == hashcodes[ti]_
Frame 1 ID = 99 , Crc=0XAA55AA55 frame with mask no. 7, full CRC = 0x12341234

So _ti != lastfound_
Now last_found = ID99 lastframe_full_crc= 0x12341234
ti != lastfound function return ti

Frame 2. same as Frame 1
so _ti == lastfound_ but mask< 255
function return ti
and in this case the function should return IDENTIFY_SAME_FRAME

Am I interpreting this wrong?

**Comment by zesinger** [comment]
Thanks, I removed it, will test it and then merge.
